### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#19]
**Number of Volunteers**: 1

One volunteer should be in charge of updating the content on the home page.

**Comment by raosudha89** [comment]
The homepage should include the following:
- [ ] Introductory video / Welcome note from Program Chairs
- [ ] Video/Slides from Infrastructure Chairs describing how to navigate the website
- [ ] Overall Schedule of the conference

@hao-fang: Please add if I missed something.

**Comment by hao-fang** [comment]
We may want to embed the read-only #announcement RocketChat channel on the Home Page.
I'm not sure if it will look good though. An alternative is to make a new page of #announcement.

**Comment by raosudha89** [comment]
- [ ] Do something like ICLR did with a blurb of all elements of the conference: https://iclr.cc/virtual/index.html

**Comment by hao-fang** [comment]
@raosudha89 can you keep track of these two issues as well?

- [ ] #86 
- [ ] #87

**Comment by raosudha89** [comment]
- [ ] Find the right way to embed two videos into the homepage

Details:
I was trying to embed to two videos in this page using the code below:

 <div class="col-md-4 col-sm-12">
    <dt>Welcome message from General Chair and Program Chairs</dt><br/>
    <div id="presentation-embed" class="slp embed-responsive embed-responsive-16by9"></div>
    <script src='https://slideslive.com/embed_presentation.js'></script>
    <script>
      embed = new SlidesLiveEmbed('presentation-embed', {
      presentationId: '{{config.default_presentation_id}}',
      autoPlay: false, // change to true to autoplay the embedded presentation
      verticalEnabled: true,
      verticalWhenWidthLte: 2000,
      allowHiddenControlsWhenPaused: true,
      hideTitle: true
      });
    </script>
  </div>  
  <div class="col-md-4 col-sm-12">
    <dt>Message from Virtual Infrastructure Chairs about the new virtual conference format</dt><br/>
  </div> 

However, when I use the same id for the div and a different ids under presentationId, it does not display two videos for some reason. 

The reason I was thinking using different div id is because here is an example from ICLR page where they embed two slideslive videos and they do that using two different div ids: https://github.com/ICLR/iclr.github.io/blob/master/templates/pages/expo.html

But to do this, I need to know where is the id 'presentation-embed' defined. I am unable to find that.

**Comment by vladdy** [comment]
@hao-fang is a volunteer still needed for this?

**Comment by hao-fang** [comment]
@vladdy 
@raosudha89 is currently on this so I'll let her explain. My understanding is that this is basically done at least for the "Basic Website" task. We can improve the layout as a "Website Enhancements" if we have time #169 .

**Comment by hao-fang** [comment]
I think it looks nice enough now with #198
