### ISSUE TITLE
Figure out the right way to make the website private

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#34]
Only registered attendee can access the website during the conference.
We need to make sure other people cannot spin up a webpage using this public repo.

We have to either make this repo a private one or make some sitedata private.
If we make the repo private, then we cannot directly sync with the upstream. In addition, we cannot use GitHub action unless we use a paid plan.
So probably we have to go with the second solution, e.g., we save the sitedata on a private AWS S3 bucket. And only use them when `make deploy`.

After the conference is over, we can check in the sitedata.

**Comment by desilinguist** [comment]
@hao-fang My $.02: 

1. For our organizational plan, we are able to use 3000 minutes of GitHub actions for private repos which should be plenty if we were to take this repo private? May be you can put together an estimate of how many minutes you will need? If it turns out to be more than 3000 minutes, we might even be able to pay for it.

2. Is this really likely to be an issue? How many people will have the time, the inclination, and the resources to spin up an entirely new website from the repo _just_ to get around the (already reduced) registration fees? And if they do, we will know about it and can call them out on social media.

**Comment by hao-fang** [comment]
@desilinguist Thanks!

> @hao-fang my $0.02 here:
> 
> 1. For our organizational plan, we are able to use 3000 minutes of GitHub actions for private repos which should be plenty if we were to take this repo private? May be you can put together an estimate of how many minutes you will need? If it turns out to be more than 3000 minutes, we might even be able to pay for it.

I don't have a good estimate, it is usually 2-3m for each PR/master commit pushed the the repo. Therefore, it means we can have 1k PR/master commits, which seems to be fine.

> 2. Is this really likely to be an issue? How many people will have the time, the inclination, and the resources to spin up an entirely new website from the repo _just_ to get around the (already reduced) registration fees? Even if they do, won't we know about it and can perhaps call them out on social media?

Let's move this discussion offline.
