### ISSUE TITLE
[W9] add the workshop schedule and the external zoom link

### ISSUE THREAD

**Issue by eric-xw** [acl-org/acl-2020-virtual-conference#489]
Hi,

We noticed that the schedule of the ALVR workshop (W9) is not listed on https://virtual.acl2020.org/workshop_W9.html. Can you help fix it? The correct schedule of W9 is here: https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=1498765767.

By the way, we will have a poster session for QA and use our own zoom link for that as suggested. Below is the zoom session information. Can you also add the information to the schedule as it is better not to show it publicly? Thanks a lot!

```
Zoom session for the general discussion (Poster Session and QA):
- zoom link: (redacted)
- password: (redacted)
- time slot: 17:10-17:45 (Pacific Daylight Time, UTC−07:00) on July 9, 2020
Action item: We hope an author from your work can attend the aforementioned general discussion session of the workshop through the zoom link above
```

Thanks,
Xin

**Comment by raosudha89** [comment]
The workshop schedule has been added - https://github.com/acl-org/acl-2020-virtual-conference-sitedata/pull/203

The zoom link is still to be added.

**Comment by raosudha89** [comment]
@eric-xw  Can you make the zoom link such that no password is required to enter the meeting? We don't display passwords in our interface.

**Comment by raosudha89** [comment]
@eric-xw  I just noticed that in the schedule spreadsheet (https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=1498765767), the poster session is already included. This means that the poster session will use the same zoom link that is used for the rest of the live session. You don't need to create a new zoom meeting link.

Only those poster sessions that have several parallel tracks were asked to schedule separate zoom meetings since the zoom link included by slideslive can have on session at a time.

Since W9 has only one session, it will be included within the main zoom meeting used for the rest of workshop.

Hope that is clear. Please let me know otherwise.

**Comment by eric-xw** [comment]
Hi @raosudha89, our poster session dose have multiple parallel tracks, so we will use our own zoom room where breakout rooms are available.

**Comment by raosudha89** [comment]
@eric-xw  I see, in that case you will need to ask slideslive to remove that session from their schedule. Because right now they are assuming that session is include in their zoom link.

**Comment by raosudha89** [comment]
Also, note that the zoom link that SlidesLive provides can have breakout rooms. Just that they can livestream only the main zoom meeting. They won't be livestreaming the breakout sessions.

**Comment by eric-xw** [comment]
Oh really? We were told by SlidesLive that we have to use our own Zoom room to host the breakout rooms. Maybe let's keep this one as it was already set up and the instructions were already sent to the paper authors. Thanks.

**Comment by raosudha89** [comment]
I see. I think there is some confusion. Okay, we can use this meeting link for your poster session. But can you make the meeting link such that one does not need a password to enter it? We don't display password in our website interface at the moment.

**Comment by eric-xw** [comment]
Sure. We have turned off the password for the zoom room.

**Comment by raosudha89** [comment]
@eric-xw  Great, thanks.

**Comment by eric-xw** [comment]
Thanks for your help!
