### ISSUE TITLE
[W20] Late pre-recorded presentations?

### ISSUE THREAD

**Issue by kverspoor** [acl-org/acl-2020-virtual-conference#514]
Due to our process, we are currently making final decisions about presentations in the workshop. I understand that we have long missed the deadline so am looking for best practice advice about the presentations currently being prepared.

I'm wondering whether it is still at all possible to use the SlidesLive platform to pre-record the presentations, or whether we should simply ask the presenters to record themselves and send us the video file (for live sharing during the Zoom session)?

**Comment by raosudha89** [comment]
@kverspoor  This is a question for SlidesLive. Although at this point, given all the different things they are managing, it may be hard for them to get this done in time. So if the presenter is okay with live sharing during zoom session, that might be the easiest at this point. 

If the presenter really prefers to pre-record, then please do the following:

1. Email Jarda at (jarda@slideslive.com) and ask if he can share a link with the presenter to pre-record. 
2. If he agrees, then please ask them to update [this spreadsheet] (https://docs.google.com/spreadsheets/d/1mnkvwYGcramosUflCRlVdgzUPIUSfkqUDpDTa5Faslg/edit#gid=1249246662)
3. Once Jarda has updated the spreadsheet, please let us know here so that we can update the virtual website with the video ID.

**Comment by kverspoor** [comment]
FYI, Jarda has indicated that this can no longer be accommodated, so I think we can close the ticket.
