### ISSUE TITLE
[W9] Update schedule

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#556]
There is some change on their schedule.

![image](https://user-images.githubusercontent.com/9957482/86833643-a7000580-c04e-11ea-9823-8bf9d16f6af5.png)

**Comment by eric-xw** [comment]
@hao-fang Thanks! But it might be better to refer to the schedule on the Google sheet: https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=1498765767.

**Comment by raosudha89** [comment]
Looks like W9 has been again updated. Lucia Specia instead of Yonaton Bisk -- https://docs.google.com/spreadsheets/d/1BbjMuZyROC973mukGks45h4bwZwDziJmv8B1RNLfz1Q/edit#gid=1498765767

**Comment by eric-xw** [comment]
Hi @raosudha89, it seems the W9 schedule on the website has not been updated yet (https://virtual.acl2020.org/workshop_W9.html) and Lucia's talk video cannot be watched there. Thanks!

**Comment by raosudha89** [comment]
@eric-xw  The website will be updated sometime later tonight. We update the website only once a day at night where we push all changes together at once after carefully checking that the changes do not break existing pages. 

I just closed this issue because we have merged the required code into the master branch. But the website will be update only after we do the night release.

**Comment by eric-xw** [comment]
Got it. Thanks!
