### ISSUE TITLE
[W20] Date/time on the website incorrect

### ISSUE THREAD

**Issue by kverspoor** [acl-org/acl-2020-virtual-conference#561]
I see that W20 is now listed as July 10: https://virtual.acl2020.org/workshops.html#tab-july10

We had been told previously it would be July 09, and have been informing presenters as such.
It appears to be shifted by 24 hours: it should be 5:30-9:30pm PDT July 09 (10:30-14:30 AEST on July 10).

**Comment by raosudha89** [comment]
@kverspoor  This is indeed a mistake from our end. Thanks for catching this. We will fix this today. Sorry about it.

**Comment by kverspoor** [comment]
Thanks so much. If you could also remove "Raina MacIntyre" from the Organizers list that would also be appreciated; she is no longer involved. (But this is not critical)

**Comment by raosudha89** [comment]
@kverspoor  Sure, we will update the organizers list.

**Comment by kverspoor** [comment]
It's still showing the incorrect time for me? https://virtual.acl2020.org/workshop_W20.html 
(I refreshed and opened a new private window, just in case)

**Comment by raosudha89** [comment]
@kverspoor We are yet to push the changes to the live website. We do this every night. So you will see the changes by late tonight. 

Here is how the W20 page will look like after we push the change. And we have removed the July 5/9/10 tabs in the new version since it could be confusing for workshops like W20 which would start on July 9 for say people in Seattle but it will start on July 10 for some others say in India. 

![image](https://user-images.githubusercontent.com/7291397/86877750-50b9b380-c09c-11ea-9de4-967da4c3b2d3.png)

**Comment by hao-fang** [comment]
@kverspoor I just push the new release. It should be updated now.
During the conference time, our website is not updated in real-time because we need to exercise extra carefulness to check all changes does not break any existing pages. Therefore, we only schedule the update every night PST.

**Comment by kverspoor** [comment]
Makes sense, thanks! Sorry, I misunderstood the previous response.

**Comment by hao-fang** [comment]
@kverspoor no problem! @raosudha89 did all the work :)
