### ISSUE TITLE
[Workshops] Verify zoom links

### ISSUE THREAD

**Issue by raosudha89** [acl-org/acl-2020-virtual-conference#575]
- Go to each workshop page. E.g. https://virtual.acl2020.org/workshop_W2.html
- Click on 'Join Zoom Meeting' for each live session (see below)
![image](https://user-images.githubusercontent.com/7291397/86948224-affddf00-c101-11ea-8d88-1b890b50c9e6.png)

- Verify that the zoom meeting opens with the correct meeting name (see below for W2)

![image](https://user-images.githubusercontent.com/7291397/86948333-d1f76180-c101-11ea-9295-193c3ebc9222.png)

**Comment by tlikhit** [comment]
I've looked through all meetings and all titles seem to be correct. Some minor comments:
- W9's second session, which goes through UC Berkeley's zoom, doesn't list event information but I'm assuming that the link is correct.
- Session 2 and 3 for W2 and Session 3 for W10 are listed as occurring on 10th July on the websites(GMT) but the zoom links list them as belonging to the "Q&A D5 9th" category. I'm assuming this is because PDT or earlier time zone is being used.

**Comment by raosudha89** [comment]
Thanks @tlikhit 

- The link is correct and since W2 organizers created it, they should be fine with event information not being listed
- Ya, that is because they are using the same zoom link for all sessions of W2. Since this is managed by SlidesLive, we don't have to worry about it.

Closing this now.
