### ISSUE TITLE
[BUG] Invalid 'X-Frame-Options' header

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#59]
**Number of Volunteers**: 1

On the `chat.html` page, it shows the `Invalid 'X-Frame-Options' header` error.
We probably need to change the RocketChat setting: "General" -> "Options to X-Frame-Options".

![image](https://user-images.githubusercontent.com/9957482/84467444-06761b80-ac31-11ea-9f1c-6e99ec962430.png)

References:
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Syntax

**Comment by stupid-2020** [comment]
It sounds this bug is fixed by RocketChat:

![image](https://user-images.githubusercontent.com/66775489/84748195-e062c980-afea-11ea-9d5d-625bf0ef826d.png)

But how could I access acl2020.rocket.chat?

Reference:
-  [Livechat widget and headers #6448](https://github.com/RocketChat/Rocket.Chat/issues/6448)

**Comment by hao-fang** [comment]
@stupid-2020 Ah, thanks for digging up the information! Let me reach out to the RocketChat support team then to see if they know how to fix this.
I'll post update here.

**Comment by hao-fang** [comment]
Closing this since it seems to be a RocketChat problem which we don't have any control.
Disable restrictions on access inside any iframe seems to make the error go away, but I don't know exactly what it means.

![image](https://user-images.githubusercontent.com/9957482/84864148-132cb200-b02b-11ea-85c9-48f001ca9418.png)
