### ISSUE TITLE
Add the SlidesLive ID for main conference papers

### ISSUE THREAD

**Issue by hao-fang** [acl-org/acl-2020-virtual-conference#88]
**Number of Volunteers: 1**

We've got the mapping from SubmissionID <-> SlidesLive presentation IDs.
We will need to add this information in our `sitedata_acl2020`.
I'll send the file via email to the volunteer who can work on this issue.

**Comment by penny9287** [comment]
I can work on this issue.

**Comment by penny9287** [comment]
@hao-fang  Hi, I want to know if I should create a new csv file to map the SubmissionID to SlidesLive presentation ID or just insert the SlidesLive presentation ID into the current paper.csv? Moreover, I can't access the "sitedata_acl2020" repo.

**Comment by hao-fang** [comment]
> @hao-fang Hi, I want to know if I should create a new csv file to map the SubmissionID to SlidesLive presentation ID or just insert the SlidesLive presentation ID into the current paper.csv?

@GuyAglionby @georgepar -- Do you have any advice on this one since you have been working on these related files?

> Moreover, I can't access the "sitedata_acl2020" repo.

@penny9287 I just added you to that repo.

**Comment by GuyAglionby** [comment]
Seems reasonable to just add a new column to `papers.csv`, maybe by editing https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/paper_import.py so we can easily regenerate the file in one go if necessary.

**Comment by hao-fang** [comment]
> Seems reasonable to just add a new column to `papers.csv`, maybe by editing https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/paper_import.py so we can easily regenerate the file in one go if necessary.

@penny9287 Can you try to do that? We would like to get this done before June 22. Thanks!

**Comment by penny9287** [comment]
Yes, I can do that.------------------ 原始邮件 ------------------发件人: Hao Fang  <notifications@github.com>发送时间: 2020年6月20日 12:41收件人: acl-org/acl-2020-virtual-conference <acl-2020-virtual-conference@noreply.github.com>抄送: penny9287 <21gram0807@gmail.com>, Mention <mention@noreply.github.com>主题: 回复：[acl-org/acl-2020-virtual-conference] Add the SlidesLive ID formain conference papers (#88)

Seems reasonable to just add a new column to papers.csv, maybe by editing https://github.com/acl-org/acl-2020-virtual-conference/blob/master/scripts/paper_import.py so we can easily regenerate the file in one go if necessary.

@penny9287 Can you try to do that? We would like to get this done before June 22. Thanks!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/acl-org/acl-2020-virtual-conference/issues/88#issuecomment-646940369",
"url": "https://github.com/acl-org/acl-2020-virtual-conference/issues/88#issuecomment-646940369",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by penny9287** [comment]
@hao-fang  Hi, I created a new csv file named "papers_with_slide_id". The SlidesLive presentation IDs are inserted into the last column.
[papers_with_slide_id.zip](https://github.com/acl-org/acl-2020-virtual-conference/files/4807765/papers_with_slide_id.zip)
